### ISSUE TITLE
【依頼】chatspace挙動確認

### ISSUE THREAD

**Issue by masaaki1130** [masaaki1130/chat-space#9]
#IPアドレス
13.113.199.30

**Comment by miyu-yamamoto** [comment]
曽我部さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう**
　一度リロードするとそれ以降は自動更新できようになっています
<img width="450" alt="スクリーンショット 2020-06-16 10 12 07" src="https://user-images.githubusercontent.com/59544869/84997021-002ff400-b189-11ea-9c70-bc7072054d79.png">

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by masaaki1130** [comment]
autoReload.jsのlet last_message_id = $('.messagefile:last').data("message-id") ||0;
||0;を追加して１回目のメッセージじも反応する様にしました。

**Comment by miyu-yamamoto** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
